package models;

// Generated 2014-4-4 11:59:10 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Entity;
import play.db.jpa.Model;

/**
 * TDictMaritals generated by hbm2java
 */
@Entity
public class t_dict_maritals extends Model {
	private static final long serialVersionUID = -7899646387404760596L;
	public String name;
	public String code;
	public String description;
	public boolean is_use;
}
