package models;

// Generated 2014-4-10 8:48:31 by Hibernate Tools 3.4.0.CR1

import play.db.jpa.Model;

/**
 * VMessageTemplateScenariosId generated by hbm2java
 */

public class v_message_template_scenarios extends Model {

	private static final long serialVersionUID = -7810138354135156306L;

	public String title;
	
	public long scenarios_id;
	
	public String content;
	
	public String scenarios;
	
	public int status;
	
	public int type;

}
